// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_4_DB.Models
{
    public partial class Classes
    {
        public string ClassId { get; set; }
        public string InstructorId { get; set; }
        public string ClassName { get; set; }
        public string AttendanceType { get; set; }
    }
}