// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_4_DB.Models
{
    public partial class Instructors
    {
        public string InstructorId { get; set; }
        public string IfirstName { get; set; }
        public string IlastName { get; set; }
        public string Iemail { get; set; }
        public byte IsAdviser { get; set; }
    }
}