// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group_4_DB.Models
{
    public partial class StudentClasses
    {
        public string StudentId { get; set; }
        public string ClassId { get; set; }
    }
}